name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          gcc --version
          make --version
      - name: List files
        run: ls -al
      - name: Build
        run: make -B V=1
